services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/deploi_db
      - NODE_ENV=development
      - JWT_SECRET=deploi-super-secret-key
      - PORT=${PORT:-3000}
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && npm run start:dev"

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=deploi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: